spring:
  application:
    name: skv-cloud-api
  datasource:
    url: jdbc:mysql://localhost:3306/pocdb
    username: root
    password: Srik@nth
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect